version: '3.8'
services: 
  api:
    container_name: api
    restart: always
    build: .
    ports: 
      - "8081:8081"
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes: 
      - apiDB:/data/db

volumes: 
  apiDB:
